version: 2

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: XiaoConstantine
    name: anthropic-go
  prerelease: auto

dist: clean
