name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write

jobs:
  docs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Check documentation syntax
        run: go doc . > /dev/null

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --enable=godot

      - name: Generate documentation
        run: |
          go install golang.org/x/tools/cmd/godoc@latest
          mkdir -p temp_docs
          godoc -http=:6060 &
          sleep 5
          wget -r -k -E -p -nH -P temp_docs http://localhost:6060/pkg/github.com/XiaoConstantine/anthropic-go/
          pkill godoc
          # Run go vet
          go vet ./...
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./temp_docs
          destination: ./_site
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v2
